List and sass
greenfox-zerda-lasers/bloodstone-bookmarks pull request #16
Opened 2017-02-01 12:56 UTC by bednayb

2017-02-01 13:33 UTC, hubudibu requested changes

2017-02-01 13:33 UTC, hubudibu commented on dist/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700" rel="stylesheet">
merge the 2 font links: `https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700|Work+Sans`

2017-02-01 13:33 UTC, hubudibu commented on dist/views/list.html
> +<section class= "listSite">
remove excess whitespace, no space around `=`

2017-02-01 13:33 UTC, hubudibu commented on dist/views/list.html
> +        <div class="plusURL">
pick one: URL or Url? I would suggest `URL`

2017-02-01 13:33 UTC, hubudibu commented on src/scss/style.scss
> +input.addUrlInput::-webkit-input-placeholder {         opacity: 0.5;
fix newline here

2017-02-01 13:33 UTC, hubudibu commented on src/scss/style.scss
> +#triangle-shadow{
rather use classes instead of ids in css

2017-02-01 13:33 UTC, hubudibu commented on src/scss/style.scss
> +	height: 0;
fix indentation

2017-02-01 13:33 UTC, hubudibu commented on src/scss/style.scss
> +  opacity: 0.9;
use rgba() text color instead to keep white background

2017-02-01 14:16 UTC, bednayb reviewed
small changes

2017-02-02 13:22 UTC, hubudibu approved these changes
👍

2017-02-02 13:22 UTC, merged